### PR TITLE
Add section for Android Databinding

### PR DESCRIPTION
**Pull request by kashban**
With the new Android Databinding support library using RIV is even simpler, especially if you want to change it dynamically through user interaction.

Taken from https://play.google.com/store/apps/details?id=de.kashban.android.picturecalendar.

### CODE REVIEW

**Comment by vinc3m1** [comment]
Yeah I don't want whole files in the README, there should just be snippets, enough to get the idea across. You can add functionality to the example app source directly though, a DataBindingFragment for example.

**Comment by kashban** [comment]
Ah, so you think this pull request is too verbose for the Readme?

**Comment by vinc3m1** [comment]
Yeah definitely too verbose for readme, but like I said you can put a section in the readme and point to a code file if you'd like. Happy to add credit where it's due too.

**Comment by kashban** [comment]
Alright, I have to dig up some time to include a databinding activity into the example app, but I'll do as soon as possible.

**Pull request closed without merging**
